version: '3'

services:
  app:
    image: docker-nextjs-ts-app
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles