import '../styles/globals.css'
import type { Metadata } from 'next'
import { Raleway, Merriweather_Sans, Lora } from "@next/font/google";
import { ThemeProvider } from '../components/theme/ThemeContext';

export const raleway = Raleway({
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-raleway',
  subsets: ['latin'],
});

export const merriweather = Merriweather_Sans({
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-merriweather',
  subsets: ['latin'],
});

export const lora = Lora({
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-lora',
  fallback: ['Times New Roman', 'Times', 'serif'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${raleway.variable} ${merriweather.variable} ${lora.variable}`}>
      <body>
        <ThemeProvider>
          <header>header</header>
          {children}
          <footer>Footer</footer>
        </ThemeProvider>
      </body>
    </html>
  )
}
